# Generated by Django 4.1.4 on 2023-01-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل کاربران', 'verbose_name_plural': 'پروفایل کاربران'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربران', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'آدرس کاربران', 'verbose_name_plural': 'آدرس کاربران'},
        ),
    ]
