# Generated by Django 4.1.4 on 2022-12-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productinfo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commnet_related', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like_related', to='product.product'),
        ),
    ]
