# Generated by Django 4.1.4 on 2022-12-27 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_alter_productcomment_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlike',
            name='user',
        ),
        migrations.AddField(
            model_name='productlike',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
