# Generated by Django 4.1.4 on 2022-12-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_like_delete_productlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
