# Generated by Django 4.1.4 on 2022-12-28 20:54

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='info',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default='hi', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
