# Generated by Django 4.1.4 on 2023-01-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_viewipadress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': 'نظر کاربر', 'verbose_name_plural': 'نظر کاربران'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'جزییات محصول', 'verbose_name_plural': 'جزییات محصولات'},
        ),
        migrations.AlterModelOptions(
            name='viewipadress',
            options={'verbose_name': 'آی پی کاربر', 'verbose_name_plural': 'آی پی کاربران'},
        ),
    ]
