# Generated by Django 4.1.4 on 2023-01-05 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_alter_product_available_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='status',
            field=models.CharField(choices=[('to do', 'To Do'), ('done', 'Done')], default='to do', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(max_length=255, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_cat',
            field=models.BooleanField(default=False, verbose_name='آیا این یک زیر دسته است؟'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='product.category', verbose_name='دسته تو در تو'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='body',
            field=models.TextField(verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commnet_related', to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
