# Generated by Django 4.1.4 on 2023-01-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_image_alter_productcomment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='تصویر محصول'),
        ),
    ]
