# Generated by Django 4.1.4 on 2023-01-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_producttags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttags',
            options={'verbose_name': 'تگ محصول', 'verbose_name_plural': 'تگ محصولات'},
        ),
        migrations.AlterField(
            model_name='producttags',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='producttags',
            name='tags',
            field=models.CharField(max_length=50, verbose_name='تگ'),
        ),
    ]
