# Generated by Django 4.1.4 on 2023-01-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_producttags_options_alter_producttags_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttags',
            name='product_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='product.productinfo', verbose_name='محصول'),
            preserve_default=False,
        ),
    ]
