# Generated by Django 4.1.4 on 2023-01-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_producttags_product_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttags',
            name='product_info',
        ),
    ]
