# Generated by Django 4.1.4 on 2023-01-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_producttags_product_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
        migrations.DeleteModel(
            name='ViewIpAdress',
        ),
    ]
