# Generated by Django 4.1.4 on 2023-01-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_product_views_delete_viewipadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_like',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک ها'),
        ),
    ]
