# Generated by Django 4.1.4 on 2023-01-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_total_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
