# Generated by Django 4.1.4 on 2023-01-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_productcomment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='status',
            field=models.CharField(choices=[('to do', 'To Do'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='to do', max_length=20, verbose_name='وضعیت'),
        ),
    ]
