# Generated by Django 4.1.4 on 2023-01-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_viewipadress_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='view', to='product.viewipadress', verbose_name='بازدید ها'),
        ),
        migrations.AlterField(
            model_name='viewipadress',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='آدرس آی پی'),
        ),
    ]
