# Generated by Django 4.1.4 on 2023-01-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_total_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر کاربر', 'verbose_name_plural': 'نظر کاربران'},
        ),
        migrations.AlterField(
            model_name='product',
            name='total_view',
            field=models.BigIntegerField(default=0, verbose_name='تعداد بازید ها'),
        ),
    ]
