# Generated by Django 4.1.4 on 2023-01-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Done', 'Done')], default='In Progress', max_length=25),
        ),
    ]
