# Generated by Django 4.1.4 on 2023-01-01 12:56

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
