# Generated by Django 4.1.4 on 2023-01-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_created_at_alter_ticket_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=100, verbose_name='تایتل'),
        ),
    ]
