# Generated by Django 4.1.4 on 2023-01-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replyticket',
            options={'verbose_name': 'جواب تیکت', 'verbose_name_plural': 'جواب تیکت ها'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
    ]
