# Generated by Django 4.1.4 on 2023-01-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_created_at_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyticket',
            name='reply_body',
            field=models.TextField(verbose_name='متن پاسخ'),
        ),
        migrations.AlterField(
            model_name='replyticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_ticket', to='ticket.ticket', verbose_name='تیکت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='body',
            field=models.TextField(verbose_name='متن تیکت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
