# Generated by Django 4.1.4 on 2023-01-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_replyticket_reply_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Done', 'Done')], db_index=True, default='In Progress', max_length=25, verbose_name='وضعیت'),
        ),
    ]
