# Generated by Django 4.1.4 on 2023-01-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_ticket_options_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Done', 'Done'), ('Failed', 'Failed')], db_index=True, default='In Progress', max_length=25, verbose_name='وضعیت'),
        ),
    ]
