# Generated by Django 4.1.4 on 2022-12-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='urmoia'),
            preserve_default=False,
        ),
    ]
