# Generated by Django 4.1.4 on 2023-01-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_paymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کد تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارشات', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم های سفارشات', 'verbose_name_plural': 'آیتم های سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name': 'تاریخچه پرداخت ها', 'verbose_name_plural': 'تاریخچه پرداخت ها'},
        ),
    ]
