# Generated by Django 4.1.4 on 2023-01-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_sent_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='ارسال شده؟'),
        ),
    ]
