# Generated by Django 4.1.4 on 2023-01-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_paymenthistory_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-create'], 'verbose_name': 'سفارشات', 'verbose_name_plural': 'سفارشات'},
        ),
    ]
